### ISSUE TITLE
大佬求个启动运行文档

### ISSUE THREAD

**Issue by walter211** [GrayXu/Virtual-Try-On-Flask#1]

**Comment by GrayXu** [comment]
Hi!

目前本项目只有后端代码，下载pretrained models放到`checkpoints/`后，就可以按照[notebook](https://github.com/GrayXu/Virtual-Try-On-Flask/blob/master/Template.ipynb)中的样例来初步运行。

更完整的文档有空会继续完成，如果有具体问题欢迎继续提问。
